### ISSUE TITLE
[FEAT] privilégier les mots entiers avant les portions de mots

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki-extension-advancedsearch#4]
**Is your feature request related to a problem? Please describe.**
Lors d'une recherche, les résultats rendent les portions de mots aussi bien que les mots entiers.

**Describe the solution you'd like**
par exemple "reve" va être trouvé dans "prévention"

**Describe alternatives you've considered**
Privilégier les réponses en premier pour les mots entiers avant de proposer les portions de mots

**Comment by acheype** [comment]
Voici une autre alternative qui me paraît meilleur car elle permettrait de réduire le nombre de résultat :
par défaut les recherches se font sur les mots entiers, ainsi une case à cocher "mots entiers" est proposé en plus du champ de recherche et l'utilisateur peut la décocher s'il veut plus de résultats.

**Comment by J9rem** [comment]
Ah oui, bonne idée, en plus c'est interactif.

**Comment by J9rem** [comment]
et peut-être même plus facile à coder

**Comment by J9rem** [comment]
Je dépose ici les deux liens que tu m'as relayés pour utiliser une notation de détection de limite de mots.
 - https://mariadb.com/kb/en/regular-expressions-overview/#word-boundaries
 - https://mariadb.com/kb/en/pcre/#special-characters
 - https://stackoverflow.com/questions/18901704/mysql-regexp-word-boundaries-and-double-quotes

**Comment by J9rem** [comment]
Au fait @acheype , j'ai continué mes réflexions sur la proposition d'attraper les mots.
J'ai compris que ce que tu proposes fonctionne pour `REGEXP`. Est-ce qu'il y a une syntaxe équivalente pour `LIKE` ?
En effet, les requêtes sont en priorité faites avec `LIKE` car c'est presque 100 fois plus rapide quand il y a plus de 1000 fiches dans la base de données.

**Comment by acheype** [comment]
Ah oui j'avais pas réfléchi à cela...

> En effet, les requêtes sont en priorité faites avec LIKE car c'est presque 100 fois plus rapide quand il y a plus de 1000 fiches dans la base de données.

C'est quelque chose que tu avais mesuré sur un de tes projets ?

Car en me renseignant là-dessus, j'ai trouvé [cet article très intéressant](http://billauer.co.il/blog/2020/12/mysql-index-pattern-matching-performance/) et apparemment le like est plus efficace quand le champ est indexé mais s'il ne l'est pas ce serait plutôt l'inverse (ce qui est le cas du champ `BODY`).

Dans le cas de mon projet, j'ai une BD d'un peu plus de 10000 entrées dans `_pages` et voici ce que j'obtiens avec les 2 versions.
Version classique, juste occurence : 
![2023-06-20 04-01 - Capture d'écran](https://github.com/YesWiki/yeswiki-extension-advancedsearch/assets/8435038/fed725f2-698c-4945-86f4-b5f26debcecc)

Version avec recherche par mot entier (cf [branche](https://github.com/YesWiki/yeswiki-extension-advancedsearch/tree/entire-word-search)) :
![2023-06-20 03-44 - Capture d'écran](https://github.com/YesWiki/yeswiki-extension-advancedsearch/assets/8435038/d54d4fe6-dab4-4c03-883e-51773fb34f48)

Je suis pas sûr de comprendre pourquoi j'ai 2 requêtes (une avec fast mode et l'autre sans) et qu'une pour la version classique. Mais c'est actuellement plus rapide avec la recherche par mot entier.

La différence de toute façon n'est pas importante (150ms) et pour moi, et même si je devais attendre 1s de plus, je préfèrerais cette version vu qu'elle me rend des résultats plus pertinent.

**Comment by J9rem** [comment]
En fait, avec une grosse base de données et un serveur SQL pas forcément réglable, je constate que la recherche dite `FAST` (premier jet) via `LIKE` se fait en moins d'une seconde alors que la recherche dite complète (second jet, pour compléter) via `REGEXP` prend 10s à 20s.
Donc je ne vais pas basculer sur `REGEXP`.

Effectivement, si un jour, nous avons une base en PostGre SQL (ou SQJ JSON natif); je suis persuadé que la recherche se fera plus vite directement avec `REGEXP`.

**Comment by acheype** [comment]
Qu'est-ce que tu appelles "grosse base de données" ?

Tu pourrais essayer le bout de code de la branche avec une base de ce type et comparer comme moi les temps de chargement des requêtes vers l'api search ?
Car ce qu'il faut voir aussi c'est que le nombre de résultat est moindre, ça réduit drastiquement le temps de recherche.

**Comment by J9rem** [comment]
a priori, j'y regarderai en septembre ou après, c'est noté de mon côté.

**Comment by J9rem** [comment]
closed because replaced by https://github.com/J9rem/yeswiki-extension-advancedsearch/issues/2
